# Example ESPHome configuration for WLED Matter Light Bridge
#
# This configuration creates a Matter-compatible light that forwards
# all commands to a WLED device via its JSON API.

esphome:
  name: wled-matter-bridge
  friendly_name: WLED Matter Bridge

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API (for Matter integration)
api:
  encryption:
    key: "YOUR_ENCRYPTION_KEY_HERE"

ota:
  - platform: esphome
    password: "YOUR_OTA_PASSWORD_HERE"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "WLED Matter Fallback"
    password: "fallbackpassword"

# Matter support (requires ESPHome 2024.5.0 or later)
esp32_ble:

# External components - the WLED Matter Light custom component
external_components:
  - source:
      type: local
      path: components
    components: [ wled_matter_light ]

# Configure the WLED Matter Light
light:
  - platform: wled_matter_light
    name: "WLED Light"
    id: wled_light
    wled_host: "192.168.1.100"  # Replace with your WLED device IP or hostname
    wled_port: 80                # Default WLED port
