# Example ESPHome configuration for WLED Matter Light Bridge
#
# This configuration creates a Matter-compatible light that forwards
# all commands to a WLED device via its JSON API.

esphome:
  name: wled-matter-bridge
  friendly_name: WLED Matter Bridge
  platformio_options:
    board_build.partitions: partitions.csv

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # Matter requires specific ESP-IDF settings
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_LWIP_MAX_SOCKETS: "16"

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API (optional - for local control and debugging)
api:
  encryption:
    key: "YOUR_ENCRYPTION_KEY_HERE"

ota:
  - platform: esphome
    password: "YOUR_OTA_PASSWORD_HERE"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "WLED Matter Fallback"
    password: "fallbackpassword"

# Matter protocol support
esp32_ble:

# Enable mDNS for Matter discovery
mdns:
  disabled: false

# Matter configuration - THIS IS THE KEY ADDITION
# This creates an actual Matter device endpoint
matter:
  vendor_id: 0xFFF1  # Vendor ID (use your own if you have one)
  product_id: 0x8001  # Product ID for light
  device_type: dimmable_light  # Matter device type

# External components - the WLED Matter Light custom component
external_components:
  - source:
      type: local
      path: components
    components: [ wled_matter_light ]

# Configure the WLED Matter Light
light:
  - platform: wled_matter_light
    name: "WLED Light"
    id: wled_light
    wled_host: "192.168.1.100"  # Replace with your WLED device IP or hostname
    wled_port: 80                # Default WLED port
